### ISSUE TITLE
🚀 Feature: Auto-generate meta previews & loading state with dist/index.html

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [FullScreenShenanigans/EightBittr#292]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/FullScreenShenanigans/EightBittr/issues?q=is%3Aissue+label%3A%22type%3A+feature%22) and found none that matched my issue.

### Expected

I'd like to have https://github.com/JoshuaKGoldberg/ChooseYourFramework/pull/13 be done automatically: so the game's preview image is used as a loading image.

In addition, the default generated `dist/index.html` file for dist games right now, as managed by `shenanigans-manager`, doesn't come with many SEO / social media `<meta>` tags. How about creating a `meta` value for `"shenanigans"` settings in the `package.json` that includes an array of `FrameTickr` tick waits and/or `InputWritr` commands to generate a social media preview image?

```json
[
  { "ticks": 10, "type": "tick" },
  { "group": "onkeydown", "key": "left", "type": "input" },
  { "ticks": 10, "type": "tick" },
  { "group": "onkeydown", "key": "down", "type": "input" }
]
```

I'm wondering if I should switch these packages to a `shenanigans.json`... #300
